// Status dos cards do dashboard

GET http://localhost:3000/api/v1/dashboard/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibG9naW4iOiJqb25hcyIsImlhdCI6MTc4OTMxODc5OSwiZXhwIjoxNzg5MzQ3NTk5fQ.R-y_CGSezi1-WnBqdW7KssKgWGM0BV3-HF3VR9A1C-A