// Status dos cards do dashboard

GET http://localhost:3000/api/v1/dashboard/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibG9naW4iOiJqb25hcyIsImlhdCI6MTc4OTI0MjAwMSwiZXhwIjoxNzg5MjcwODAxfQ.fEe7_1MMGIf3Aw8yAfrZQZGQ20jxKRmQKowG_s7KisQ